/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: virgodmonkey (https://sketchfab.com/virgodmonkey)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cassette-tape-21e23f5fe0714a98a1b76b4f6ae4eb9c
title: Cassette Tape
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cassette.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[-0.1, -0.01, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.mesh_0.geometry} material={materials.label_MTL} />
            </group>
            <group rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.mesh_1.geometry} material={materials.tex_pack_MTL} />
              <mesh geometry={nodes.mesh_2.geometry} material={materials.white_plastic_MTL} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cassette.gltf')
