/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: compost the second (https://sketchfab.com/compostthesecond)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/jukebox-8397d23c1b1c40ea867ca1a44667be37
title: jukebox
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/jukebox.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-0.19, -3.68, 9.69]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={2.9}>
          <mesh geometry={nodes.jukebox_0.geometry} material={materials.jukeboxwrap} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/jukebox.gltf')
